service: aws-lambda-sns
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
functions:
  main:
    handler: index.handler
  signal:
    handler: index.statusHandler
  status:
    handler: index.disconnectedHandler
